server:
  port: 20000

spring:
  datasource:
    url: jdbc:mysql://localhost:20001/sample?allowPublicKeyRetrieval=true&useSSL=false
    username: sample
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 20002
      repositories:
        enabled: false

logging:
  level:
    root: INFO
