version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: password
    ports:
      - "20001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sample-net

  redis:
    image: redis:7.0
    container_name: redis-local
    ports:
      - "20002:6379"
    volumes:
      - redis_data:/data
    networks:
      - sample-net



volumes:
  mysql_data:
  redis_data:

networks:
  sample-net:
    driver: bridge
